### ISSUE TITLE
unresponsive quiz

### ISSUE THREAD

**Issue by hannahemills** [learn-co-curriculum/dev-tools-super-power#4]
None of the answers buttons are responding when selected

**Comment by maxwellbenton** [comment]
Hi there @hannahemills,

I'm having difficulty reproducing the issue.  Did you mean the quiz in the previous repository (https://github.com/learn-co-curriculum/quiz-html-fundamentals)? This repo is just a readme with no quiz, so I'm going to close this issue for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
